### ISSUE TITLE
Problems with sign the Adobe CLA!

### ISSUE THREAD

**Issue by ygyryn** [adobe/cla-bot#104]
My pull request to devdocs https://github.com/magento/devdocs/pull/5869  can't be merged, because of needs to sign Adobe CLA.  I already did it twice. But it did not helped. I tried to close and reopen pull request, but it is still asking me to Sign the Adobe CLA!
See, https://github.com/magento/devdocs/pull/5869/checks?check_run_id=279874096

**Comment by filmaj** [comment]
I see  you signed the CLA twice, but both times you entered your full name into the document where it asks for your GitHub username. As such, the CLA bot cannot find your github.com username in our database.

Please sign the CLA once more and carefully read the form fields in the document. Where it says "GitHub Username" enter `ygyryn` and not `Yaroslav Gyryn`.

<img width="574" alt="Screen Shot 2019-10-29 at 1 41 17 PM" src="https://user-images.githubusercontent.com/52645/67793829-f4ed5400-fa51-11e9-8cc9-eb7e9698d784.png">

Give that a try and let me know how it goes.

**Comment by ygyryn** [comment]
Thank you, it was my mistake!
