### ISSUE TITLE
Integration tests for a public magento repo failing

### ISSUE THREAD

**Issue by filmaj** [adobe/cla-bot#107]
Seems like due to the github.com/magento/devops-cla-test-adcb repo being removed.

We need a new public repo on github.com/magento set up with both  the cla-bot and cla-bot-staging GitHub Apps installed on it.

**Comment by filmaj** [comment]
FYI @mmansoor-magento and @macdonst

**Comment by mmansoor-magento** [comment]
https://github.com/magento/devops-cla-test-public should have cla-bot and cla-bot-staging Apps installed on it now.
