### ISSUE TITLE
Submitted the "Adobe CLA" but still, this is showing not signed

### ISSUE THREAD

**Issue by singhkh** [adobe/cla-bot#142]
Hi team,

Recently, I made changes in https://github.com/AdobeDocs/experience-manager-forms-cloud-service-developer-reference documentation and submitted a pull request on GitHub.
I have already submitted the "Adobe CLA" but still, this is showing not signed?

Please check this issue.

**Comment by josh-hadley** [comment]
please see https://github.com/adobe/cla-bot/issues/140#issuecomment-1258691457
