### ISSUE TITLE
Requesting reviews in issued pull requests triggers bot twice

### ISSUE THREAD

**Issue by filmaj** [adobe/cla-bot#15]
See https://github.com/adobe/cla-bot/pull/14

Looks to be from two separate pull request events triggering the bot:

1. The pull request being opened (as expected), which has a payload that looks like this:

```
{
  "action": "opened",
  "number": 14,
  "pull_request": {
```

2. Pull request _review requested_, which has a payload that looks like this:

```
{
  "action": "review_requested",
  "number": 14,
  "pull_request": {
```

I think we should limit the checker action to only act upon pull request action:opened payloads.

**Comment by stevengill** [comment]
agreed. Want me to do this one?
