### ISSUE TITLE
submitted Adobe CLA but still showing not submitted CLA

### ISSUE THREAD

**Issue by shubhamg1996** [adobe/cla-bot#153]
### Expected Behaviour
Allow me to submit PR

### Actual Behaviour
Checks fail , Adobe CLA not signed

### Reproduce Scenario (including but not limited to)
https://github.com/AdobeDocs/experience-manager-cloud-service.en/pull/229

#### Steps to Reproduce
https://github.com/AdobeDocs/experience-manager-cloud-service.en/pull/229

#### Platform and Version
https://github.com/AdobeDocs/experience-manager-cloud-service.en/pull/229

#### Sample Code that illustrates the problem
https://github.com/AdobeDocs/experience-manager-cloud-service.en/pull/229

**Comment by shubhamg1996** [comment]
Got resolution from other resolved issue

**Comment by Nolwennig-Jeulin** [comment]
Same problem for me , resolved after reading this comment 👉 https://github.com/adobe/cla-bot/issues/140#issuecomment-1258691457 👈
