### ISSUE TITLE
Unable to raise a PR because of CLA

### ISSUE THREAD

**Issue by Vikaashkarthick-K** [adobe/cla-bot#159]
### Expected Behaviour
The CLA sign check to be done and processed.

### Actual Behaviour
CLA is not getting signed and unable to raise a PR
<img width="913" alt="image" src="https://github.com/adobe/cla-bot/assets/136694466/d2481f69-562a-4295-bc73-423a70c889f2">

### Reproduce Scenario 
Though after signing CLA form several times, still while raising PR unable to clear CLA sign check. Because of this unable to raise a PR
#### Steps to Reproduce
1. Updated the required issue details 
2. Click on merge PR

**Comment by hostep** [comment]
More specifically, this is about this pull request: https://github.com/magento/magento2/pull/37735

**Comment by hostep** [comment]
@Vikaashkarthick-K: does the [following comment](https://github.com/adobe/cla-bot/issues/140#issuecomment-1258691457) help? Make sure the 2 bullet points have been checked.

If that doesn't help, we may need to somehow try to get more attention from Adobe to this issue....

**Comment by Vikaashkarthick-K** [comment]
@hostep the following checks in the mentioned comment have been checked.
Everything mentioned over there is given properly.
Still the issue persists.

**Comment by hostep** [comment]
@josh-hadley: any idea, can this be looked into?
This is about CLA checks not working in https://github.com/magento/magento2/pull/37735
Also https://github.com/magento/magento2/pull/37837 seems to have the same problem.

(these comes from discussions on the Magento Slack workspace)

Thanks!

**Comment by josh-hadley** [comment]
Closing; assuming it's been resolved. Please re-open and comment if not.
