### ISSUE TITLE
Non-employee with signed CLA does not work

### ISSUE THREAD

**Issue by hirenoble** [adobe/cla-bot#17]
cla-bot is not working as expected. 
Sign-in with non-employee signed account.
Created a pull request on cla-bot-playground.
Though the CLA is signed and this id has been tested successfully earlier, it asked me to sign the CLA again.
Seems like Adobe sign query api is failing and returning empty results instead of agreement_ids.
![image](https://user-images.githubusercontent.com/3747836/50849215-8e1c7400-1333-11e9-9b98-18bae4986e4c.png)

Re-opening a pull request is being ignored.

**Comment by hirenoble** [comment]
![image](https://user-images.githubusercontent.com/3747836/50849241-a1c7da80-1333-11e9-8141-7b15f44e4ce5.png)

**Comment by stevengill** [comment]
We can close this I think now
