### ISSUE TITLE
Don't request greenkeeper and other bots to sign cla

### ISSUE THREAD

**Issue by stevengill** [adobe/cla-bot#19]
Look into whitelisting PRs from bots. Example https://github.com/adobe/aio-cli-plugin-console/pull/15

**Comment by shazron** [comment]
Merged that PR already. Here is what it looked like:
![screenshot_2019-01-11 update jest-junit to the latest version by greenkeeper pull request 15 adobe aio-cli-plugin-c](https://user-images.githubusercontent.com/36107/51009007-3f681780-1589-11e9-99c8-81bc8ce6d156.png)

**Comment by shazron** [comment]
Is the CLA bot online? Greenkeeper not verified here: https://github.com/adobe/aio-cli-plugin-config/pull/22

**Comment by filmaj** [comment]
Yes, it's online. CLA bot ignored all bot accounts, so it shouldn't answer to the PRs at all. I'm surprised there's a 'waiting for a response' check there - previously, github didn't render the check at all when a bot issued a PR.

**Comment by shazron** [comment]
I can try closing and re-opening the PR to see if it still occurs. But if it still occurs, it will be a problem (not sure where the error lies).

**Comment by shazron** [comment]
I tried a regular user PR, the CLA bot responded. Did the close/re-open of the PR, nothing changed for the CLA bot response. I'll chalk this off to a one-off glitch since I can just circumvent the required check for the bot.

**Comment by filmaj** [comment]
Yeah, all bot PRs get a 202 response which should be HTTP speak for 'ignore this' https://github.com/adobe/cla-bot/commit/8f7957c47861c854345712f8b805576060a12710

**Comment by shazron** [comment]
Cool - I'll file a new issue if this reoccurs :)
