### ISSUE TITLE
Use internal mapping to confirm if github user is adobe employee

### ISSUE THREAD

**Issue by stevengill** [adobe/cla-bot#25]
This is an enhancement for later. We should create a service that exposes our github ID to AdobeID mappings and checks against that service to confirm if a pull request was sent by an Adobe Employee. For now, we just check to see if the user is part of the org. 

Related to https://github.com/adobe/cla-bot/issues/20

**Comment by filmaj** [comment]
I don't think this is going to work as that mapping will always be incomplete. Closing this.
