### ISSUE TITLE
Checker promise resolution is undefined when deferring to `action_required`

### ISSUE THREAD

**Issue by filmaj** [adobe/cla-bot#26]
Two things:

1. Currently in `checker.js`, the `action_required` function does not return anything, but we resolve the `checker` action with its return value (there are two instances of `resolve(action_required())` - so we resolve with `undefined`. I think this is what is leading to certain HTTP 204 w/ empty body responses to github webhook events.
2. The `action_required` method depends on its own promise resolution, so it should be returning the promise, and then whenever it is invoked, it should be chained up to a promise chain itself.

**Comment by hirenoble** [comment]
Hi Fil, I do see two instances of `resolve(action_required(ow, args))` and it does return response based on the setgithubcheck function.     
`return {
      body: check.title
    };`
I think we need to debug more for an empty response.

**Comment by hirenoble** [comment]
I tested the below snippet to validate the code and it worked fine for me. action_required is written and implemented in checker.js in similar way. It will be a good learning for me to understand the chaining of promise in this scenario. 
```js
function main(params)
{
    return new Promise(function(resolve,reject){
        resolve(test("hi"));
    });
}

function test(arg)
{
    return {body:arg};
}
```

**Comment by filmaj** [comment]
Sure thing @hirenoble !

The difference is that in your example, `test` returns _immediately_, whereas in checker, `action_required` does not return anything.. yes, there are return statements inside `action_required`, but only inside the promise chain (inside `then` and `catch`).

The correct way to set up `action_required` is a very minor fix: it should `return` the promise it is invoking. So, the very first line should change from `ow.actions.invoke({...})` to `return ow.actions.invoke({...})`. Additionally, we should not pass the result of `action_required` into `resolve`, but rather chain `action_required` into the rest of the promise chain, and in an additional `then`, get the result returned from `action_required` and finally resolve with that.

I'll send a PR with this and ping you on it to better explain it.

**Comment by filmaj** [comment]
I think we fixed it!
