### ISSUE TITLE
Adobe employee check should use github.com/adobe org as backup org to check for PRs incoming to orgs other than github.com/adobe

### ISSUE THREAD

**Issue by filmaj** [adobe/cla-bot#44]
See https://github.com/AdobeDocs/experience-manager-htl.en/pull/2 for details of this edge case in action. Radu is a member of github.com/adobe, but not adobedocs, and issued a PR to adobedocs, and got told to sign the CLA.

Suggestion: for orgs other than github.com/adobe, if the github org membership check fails, issue an additional org membership check for github.com/adobe as well before going through the flow of verifying signed CLA documents in Adobe Sign.

**Comment by stevengill** [comment]
I think we originally tried to check github.com/adobe for all requests but ran into issues when the bot was installed on different orgs. Something about private members not popping up.

**Comment by filmaj** [comment]
That's right. Still, this additional check-adobe-org-for-non-adobe-orgs backup would work in the case that membership is public. I think it's worth implementing.
