### ISSUE TITLE
autodeploy runtime actions via travis

### ISSUE THREAD

**Issue by stevengill** [adobe/cla-bot#5]
setup autodeploy on commit

**Comment by filmaj** [comment]
This one is related to enabling greenkeeper on the repo, too, as we need some CI to be able to do that (see #1).

I'm also thinking of changing the config code a little bit to either look for keys using the config.json file, or fallback to using an environment variable. This way we can safely store the keys in Travis' secure environment variables, and that paves the way to continuous deployment.

I think I will add a few basic tests as part of this work, too.

**Comment by filmaj** [comment]
This is done!
