### ISSUE TITLE
Report status via Checks API

### ISSUE THREAD

**Issue by webknjaz** [adobe/cla-bot#50]
It'd be cool to visualize the status and instructions on the Checks page.

**Comment by filmaj** [comment]
It is rendering to the checks page, see e.g. https://github.com/adobe/cla-bot/pull/49/checks?check_run_id=84615061

If this is doing what you expect, can I close the issue?

**Comment by webknjaz** [comment]
Oh, right. Thanks! I was trying to find any mentions via search and failed. This should probably be mentioned in the readme :)

**Comment by filmaj** [comment]
The overview in the README mentions which serverless action sets checks on pull requests 'using the Checks API' 😄

**Comment by webknjaz** [comment]
Odd, Ctrl+F has failed me :)
