### ISSUE TITLE
Update contribution guidelines and pull request template

### ISSUE THREAD

**Issue by filmaj** [adobe/cla-bot#65]
With the CI/CD in place for this repo, should ensure it is documented properly.

Things to doc:
- the unit vs integration testing
- the reqs for the integration tests (multiple personal access tokens representing different levels of github membership)
- PRs from forks should be reviewed and, if nothing malicious exists in the code, should be pushed to the origin to trigger full integration testing via travis.

**Comment by prashcr** [comment]
I'd like to work on this :)
