### ISSUE TITLE
signwebhook failing due to lookup action requiring username be provided

### ISSUE THREAD

**Issue by filmaj** [adobe/cla-bot#96]
The `signwebhook` action is failing because it invokes `lookup` without providing the username as a parameter, so therefore the code on line 66 inside `lookup.js` fails.

FYI @prashcr

**Comment by filmaj** [comment]
@prashcr I just confirmed that this bug was introduced as part of your parallelization / cancelling in-flight requests work. As such I am going to revert to SHA 72c1f99 to at least fix the issue in the short term.

**Comment by filmaj** [comment]
We can continue to work on the parallelization effort  in a separate thread, though perhaps it may not be worth it...

**Comment by prashcr** [comment]
Sorry about that, I noticed `lookup` was being called in `checker` and called called it a day. I didn't notice the call in `signwebhook` 😕

It seems like a trivial bug, so I'll give it a 2nd try.

**Comment by filmaj** [comment]
That's OK. Software dev comes with bugs and I should have caught it during review anyways :)

To be honest, I'm not sure if the added complexity to the code is worth the performance benefits (if any). I wouldn't put this super high on the todo list to be frank.
